[project]
name = "minechat"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "aiofiles>=25.1.0",
    "python-dotenv>=1.2.1",
    "ruff>=0.14.8",
]
